# Generated by Django 4.1.4 on 2022-12-15 14:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeofclothes',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='typeofclothes',
            name='slug',
            field=models.SlugField(default='bound-method-field__str__-of-djangodbmodelsfieldscharfield', max_length=250),
        ),
    ]
