# Generated by Django 4.1.4 on 2022-12-15 15:38

import autoslug.fields
from django.db import migrations
import transliterate.utils


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_typeofclothes_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeofclothes',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='type_name', slugify=transliterate.utils.slugify),
        ),
    ]
