# Generated by Django 4.1.4 on 2022-12-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothings',
            name='size_l',
            field=models.PositiveIntegerField(blank=True, help_text='Количество данного размера', null=True, verbose_name='L'),
        ),
        migrations.AlterField(
            model_name='clothings',
            name='size_m',
            field=models.PositiveIntegerField(blank=True, help_text='Количество данного размера', null=True, verbose_name='M'),
        ),
        migrations.AlterField(
            model_name='clothings',
            name='size_s',
            field=models.PositiveIntegerField(blank=True, help_text='Количество данного размера', null=True, verbose_name='S'),
        ),
        migrations.AlterField(
            model_name='clothings',
            name='size_xl',
            field=models.PositiveIntegerField(blank=True, help_text='Количество данного размера', null=True, verbose_name='XL'),
        ),
        migrations.AlterField(
            model_name='clothings',
            name='size_xs',
            field=models.PositiveIntegerField(blank=True, help_text='Количество данного размера', null=True, verbose_name='XS'),
        ),
    ]
